"""schema inicial

Revision ID: 26bfcecb99ad
Revises: 
Create Date: 2026-08-24 22:00:29.035735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26bfcecb99ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('email_responsavel', sa.String(length=255), nullable=False),
    sa.Column('nome_responsavel', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=10), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('feriados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('uf', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('ds_feriado', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'uf', 'cidade', 'tipo', 'ds_feriado', name='uq_feriados_data_uf_cidade_tipo_ds')
    )
    op.create_table('feriados_sincronizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(length=10), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uf', 'cidade', 'ano', name='uq_feriados_sync_uf_cidade_ano')
    )
    op.create_table('solicitacoes_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_responsavel', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome_hospital', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo_item', sa.String(length=100), nullable=False),
    sa.Column('descricao_item', sa.String(length=500), nullable=False),
    sa.Column('unidade_medida', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_item', name='uq_itens_empresa_codigo')
    )
    op.create_table('modelos_treinados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('algoritmo', sa.String(length=50), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('treinado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('classificacao_abc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('classe', sa.String(length=1), nullable=False),
    sa.Column('valor_acumulado_percentual', sa.Float(), nullable=False),
    sa.Column('calculado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumos_tratados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('quantidade_total', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('local_estoque', sa.String(length=255), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'item_id', 'periodo', 'local_estoque', name='uq_tratado_chave')
    )
    with op.batch_alter_table('consumos_tratados', schema=None) as batch_op:
        batch_op.create_index('ix_tratado_empresa_periodo', ['empresa_id', 'periodo'], unique=False)

    op.create_table('importacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_registros', sa.Integer(), nullable=False),
    sa.Column('registros_validos', sa.Integer(), nullable=False),
    sa.Column('registros_invalidos', sa.Integer(), nullable=False),
    sa.Column('erros', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('previsoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('quantidade_prevista', sa.Float(), nullable=False),
    sa.Column('intervalo_inferior', sa.Float(), nullable=True),
    sa.Column('intervalo_superior', sa.Float(), nullable=True),
    sa.Column('gerado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_treinados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('previsoes', schema=None) as batch_op:
        batch_op.create_index('ix_previsao_empresa_periodo', ['empresa_id', 'periodo'], unique=False)

    op.create_table('consumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('importacao_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('local_estoque', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacoes.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumos', schema=None) as batch_op:
        batch_op.create_index('ix_consumo_empresa_item_data', ['empresa_id', 'item_id', 'data'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumos', schema=None) as batch_op:
        batch_op.drop_index('ix_consumo_empresa_item_data')

    op.drop_table('consumos')
    with op.batch_alter_table('previsoes', schema=None) as batch_op:
        batch_op.drop_index('ix_previsao_empresa_periodo')

    op.drop_table('previsoes')
    op.drop_table('importacoes')
    with op.batch_alter_table('consumos_tratados', schema=None) as batch_op:
        batch_op.drop_index('ix_tratado_empresa_periodo')

    op.drop_table('consumos_tratados')
    op.drop_table('classificacao_abc')
    op.drop_table('usuarios')
    op.drop_table('modelos_treinados')
    op.drop_table('itens')
    op.drop_table('solicitacoes_acesso')
    op.drop_table('feriados_sincronizacoes')
    op.drop_table('feriados')
    op.drop_table('empresas')
    # ### end Alembic commands ###
