"""remove tabela feriados_sincronizacoes

Revision ID: 8215c192798c
Revises: e25201dd0200
Create Date: 2026-09-20 19:37:44.578539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8215c192798c'
down_revision: Union[str, Sequence[str], None] = 'e25201dd0200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feriados_sincronizacoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriados_sincronizacoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uf', sa.VARCHAR(length=10), nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ano', sa.INTEGER(), nullable=False),
    sa.Column('sincronizado_em', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uf', 'cidade', 'ano', name=op.f('uq_feriados_sync_uf_cidade_ano'))
    )
    # ### end Alembic commands ###
