"""adiciona logs_execucao

Revision ID: e25201dd0200
Revises: 26bfcecb99ad
Create Date: 2026-08-25 22:24:54.944358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25201dd0200'
down_revision: Union[str, Sequence[str], None] = '26bfcecb99ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_execucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.String(length=1000), nullable=False),
    sa.Column('contexto', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_execucao', schema=None) as batch_op:
        batch_op.create_index('ix_logs_empresa_modulo', ['empresa_id', 'modulo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_execucao', schema=None) as batch_op:
        batch_op.drop_index('ix_logs_empresa_modulo')

    op.drop_table('logs_execucao')
    # ### end Alembic commands ###
